services:
  - type: web
    name: b2b-best-of-beauty
    runtime: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "10000"
      - key: OWNER_MOBILE
        value: "+917904183225"
      - key: OWNER_EMAIL
        value: "cecsbaraths24@gmail.com"
